sudo: required

services:
  - docker

# Omit running tests on temporal branches
branches:
  except:
    - /^tmp/

# Even though we run everything inside docker Travis require
# us to pick a language else it will pick Ruby by default
language: python
python:
  - "2.7"

env:
  - TEST_SLEEPS="0.7"
  - DOCKER_COMPOSE_VERSION=1.7.1

before_install:
  - travis_retry ./test/before_install_setup
  - travis_retry ./test/before_install_build

install:
  - ./test/install

script:
  - ./test/script

# cleanup though doesn't seem to be necessary in Travis infra
after_script:
  - ./test/after_script
